services:

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - keycloak
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
        - '8081:8080'


  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - APP_DB=$DB_NAME
      - KEYCLOAK_DB=$KEYCLOAK_DB
    ports:
      - '5432:5432'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d



  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: [ "start-dev" , "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/$KEYCLOAK_DB
      KC_DB_USERNAME: $DB_USERNAME
      KC_DB_PASSWORD: $DB_PASSWORD
      KC_BOOTSTRAP_ADMIN_USERNAME: $KEYCLOAK_USER
      KC_BOOTSTRAP_ADMIN_PASSWORD: $KEYCLOAK_PASSWORD
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    volumes:
      - ./tmp/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - db
