services:

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - keycloak
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
        - '8081:8081'

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - '5432:5432'


  keycloak-db:
    image: 'postgres:latest'
    container_name: keycloak-db
    environment:
      POSTGRES_DB : $KEYCLOAK_DB
      POSTGRES_USER : $KEYCLOAK_DB_USERNAME
      POSTGRES_PASSWORD : $KEYCLOAK_DB_PASSWORD


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: [ "start-dev" ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/$KEYCLOAK_DB
      KC_DB_USERNAME: $KEYCLOAK_DB_USERNAME
      KC_DB_PASSWORD: $KEYCLOAK_DB_PASSWORD
      KEYCLOAK_ADMIN: $KEYCLOAK_USER
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_PASSWORD
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
